name = "tracewayapp"
main = "./functions/worker.ts"
compatibility_date = "2025-02-01"

routes = [
  { pattern = "tracewayapp.com", zone_name = "tracewayapp.com", custom_domain = true }
]

[vars]
SENDGRID_FROM_EMAIL = "dusan@tracewayapp.com"
SENDGRID_TO_EMAIL = "dusan@tracewayapp.com"
NEXT_PUBLIC_CALENDLY_URL = "https://calendly.com/dusan-tracewayapp/30min?back=1&month=2026-04"

[observability]
enabled = true

[observability.traces]
enabled = true
head_sampling_rate = 1
destinations = ["traceway"]

[assets]
directory = "./out"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
